config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'

  root to: "pages#home"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  get "up" => "rails/health#show", as: :rails_health_check
  get "signup_page" => "pages#signup_page", as: :signup_page
  get 'how_does_it_work', to: 'pages#how_does_it_work', as: :how_does_it_work
  get 'about_us', to: 'pages#about_us', as: :about_us
  get 'why_talkroom', to: 'pages#why_talkroom', as: :why_talkroom
  get 'contact_us', to: 'pages#contact_us', as: :contact_us
  put 'contact_us', to: 'pages#contact_us', as: :contact_us_create
  delete 'signout', to: 'users/sessions#destroy', as: :signout



  devise_for :users, path: 'users', controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
    }

    devise_for :counsellors, path: 'counsellors', controllers: {
      registrations: "counsellors/registrations",
      sessions: "counsellors/sessions",
      }

      devise_for :supervisors, path: 'supervisors', controllers: {
        registrations: "supervisors/registrations",
        sessions: "supervisors/sessions",
        }

  resources :counsellors, only: [] do
    member do
      get 'profile', to: 'counsellors#profile', as: :profile
    end
  end

  resources :users, only: [] do
    member do
      get 'profile', to: 'users#profile', as: :profile
    end
  end

  resources :client_chatrooms, only: [:show, :create] do
    resources :messages, only: :create
  end
  resources :appointments, only: [:new, :create, :edit, :update, :destroy, :show,]

  resources :counsellor_chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :contacts, only: [:new, :create]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer mt-5 pt-4 pb-2">
  <div class="container">
    <div class="row">
      <div class="col-md-4 mb-3">
        <h5>Company</h5>
        <ul class="list-unstyled">
          <li><%= link_to 'About Us', about_us_path, class: 'footer-link text-muted' %></li>
          <li><%= link_to 'Contact', contacts_new_path, class: 'footer-link text-muted' %></li>
          <li><%= link_to 'Careers', '#', class: 'footer-link text-muted' %></li>
        </ul>
      </div>
      <div class="col-md-4 mb-3">
        <h5>Support</h5>
        <ul class="list-unstyled">
          <li><%= link_to 'FAQ', '#', class: 'footer-link text-muted' %></li>
          <li><%= link_to 'Terms of Service', '#', class: 'footer-link text-muted' %></li>
          <li><%= link_to 'Privacy Policy', '#', class: 'footer-link text-muted' %></li>
        </ul>
      </div>
      <div class="col-md-4 mb-3">
        <h5>Connect with the creator</h5>
        <ul class="list-unstyled">
          <li><a href="https://www.instagram.com/luiz.cunhaa/" class="text-muted" target="_blank">Instagram</a></li>
          <li><a href="https://www.linkedin.com/in/luiz-cunha-560779227/" class="text-muted" target="_blank">Linkedin</i></a></li>
          <li><a href="https://github.com/Luiz-Cunha" class="text-muted" target="_blank">Github</a></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-12 text-center">
        <p class="text-muted">&copy; <%= Time.now.year %> Talkroom. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="d-flex justify-content-between w-100">
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%= image_tag 'logo-2.png', class: 'logo-nav ms-3' %>
      <% end %>
      <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse ps-4" id="navbarNav">
      <div class="d-flex justify-content-end">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item me-3">
            <%= link_to 'How Does It Work', how_does_it_work_path, class: 'nav-link' %>
          </li>
          <li class="nav-item me-3">
            <%= link_to 'Contact', contacts_new_path, class: 'nav-link' %>
          </li>
          <li class="nav-item me-3">
            <%= link_to 'About Us', about_us_path, class: 'nav-link' %>
          </li>
          <li class="nav-item me-3">
            <%= link_to 'Why TalkRoom?', why_talkroom_path, class: 'nav-link' %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= current_user.photo.attached? ? cl_image_path(current_user.photo.key) : asset_path('white-hands.png') %>" />
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Your Profile", profile_user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Edit your account", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
              </div>
            </li>
          <% elsif counsellor_signed_in? %>
            <li class="nav-item dropdown">
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= current_counsellor.photo.attached? ? cl_image_path(current_counsellor.photo.key) : asset_path('white-hands.png') %>" />
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Your Profile", profile_counsellor_path(current_counsellor), class: "dropdown-item" %>
                <%= link_to "Edit your account", edit_counsellor_registration_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_counsellor_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
              </div>
            </li>
          <% elsif supervisor_signed_in? %>
            <li class="nav-item dropdown">
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= current_supervisor.photo.attached? ? cl_image_path(current_supervisor.photo.key) : asset_path('white-hands.png') %>" />
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Your Profile", profile_user_path(current_supervisor), class: "dropdown-item" %>
                <%= link_to "Edit your account", edit_supervisor_registration_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_supervisor_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="loginDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Login
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="loginDropdown">
                <li><%= link_to "Login as Patient", new_user_session_path, class: "dropdown-item" %></li>
                <li><%= link_to "Login as Counsellor", new_counsellor_session_path, class: "dropdown-item" %></li>
                <li><%= link_to "Login as Supervisor", new_supervisor_session_path, class: "dropdown-item disabled" %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>