config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'

  root to: "pages#home"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  get "up" => "rails/health#show", as: :rails_health_check
  get "signup_page" => "pages#signup_page", as: :signup_page
  get 'how_does_it_work', to: 'pages#how_does_it_work', as: :how_does_it_work
  get 'about_us', to: 'pages#about_us', as: :about_us
  get 'why_talkroom', to: 'pages#why_talkroom', as: :why_talkroom
  get 'contact_us', to: 'pages#contact_us', as: :contact_us
  put 'contact_us', to: 'pages#contact_us', as: :contact_us_create
  delete 'signout', to: 'users/sessions#destroy', as: :signout



  devise_for :users, path: 'users', controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
    }

    devise_for :counsellors, path: 'counsellors', controllers: {
      registrations: "counsellors/registrations",
      sessions: "counsellors/sessions",
      }

      devise_for :supervisors, path: 'supervisors', controllers: {
        registrations: "supervisors/registrations",
        sessions: "supervisors/sessions",
        }

  resources :counsellors, only: [] do
    member do
      get 'profile', to: 'counsellors#profile', as: :profile
    end
  end

  resources :users, only: [] do
    member do
      get 'profile', to: 'users#profile', as: :profile
    end
  end

  resources :client_chatrooms, only: [:show, :create] do
    resources :messages, only: :create
  end
  resources :appointments, only: [:new, :create, :edit, :update, :destroy, :show,]

  resources :counsellor_chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :contacts, only: [:new, :create]

end

app/models/counsellor.rb
class Counsellor < ApplicationRecord
  has_many :appointments
  has_many :users, through: :appointments
  has_many :messages, as: :sendable
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :address, presence: true

end

app/controllers/counsellors/registrations_controller.rb
# frozen_string_literal: true

class Counsellors::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/counsellors/sessions_controller.rb
# frozen_string_literal: true

class Counsellors::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/counsellors_controller.rb
class CounsellorsController < ApplicationController
  skip_before_action :authenticate_user!, if: :check_user_type_counsellor
  before_action :authenticate_counsellor!
  def profile
    @counsellor = Counsellor.find(params[:id])
    @appointments_confirmed = @counsellor.appointments.where(confirmation: true)
    @appointments = Appointment.where(confirmation: false)
  end

  private
  def check_user_type_counsellor
    current_counsellor && counsellor_signed_in?
  end
end

app/views/counsellors/_appointment_accept.html.erb
<div class="justify-content-center">
  <h5 class="card-title"><strong><%= appointment.user.fullname %></strong></h5>
  <p class="card-text"><%= appointment.symptom %></p>
    <div class= "d-flex flex-column justity-content-center">
      <div>
        <strong>Schedule Time:</strong>
        <%= appointment.schedule_time.strftime("%B %d, %Y at %I:%M %p") %>
      </div>
      <div class="d-flex justify-content-end ms-3">
        <%= simple_form_for appointment do |f| %>
          <%= f.input :confirmation, as: :hidden, input_html: { value: true } %>
          <%= f.submit 'Accept', class: 'btn-accept' %>
        <% end %>
      </div>
    </div>
</div>

app/views/counsellors/_pending_appointments.html.erb
<div class="d-flex justify-content-center col-md-6 mb-4">
  <div class="card-appointment">
    <div class="d-flex justify-content-center py-2">
      <% if appointment.user.photo.attached? %>
        <%= image_tag cl_image_path(appointment.user.photo.key), alt: 'Profile User Photo', class: 'img-card-appointment mx-4' %>
      <% else %>
        <%= image_tag asset_path('counsellor.png'), alt: 'Default Profile Photo', class: 'img-card-appointment mx-4' %>
      <% end %>
      <% if appointment.counsellor.nil? %>
        <%= image_tag asset_path('question-mark.jpg'), alt: 'Default Profile Photo', class: 'img-card-appointment mx-4' %>
      <% else %>
        <% if appointment.counsellor.photo.attached? %>
          <%= image_tag cl_image_path(appointment.counsellor.photo.key), alt: 'Profile Counsellor Photo', class: 'img-card-appointment mx-4' %>
        <% end %>
      <% end %>
    </div>
    <div class="ps-2">
      <%= render 'counsellors/appointment_accept', appointment: appointment %>
    </div>
  </div>
</div>

app/views/counsellors/_previous_appointment_counsellor.html.erb
<div class="d-flex justify-content-center py-2">
  <div class="card-appointment-accepted">
    <div class="d-flex justify-content-center py-2">
      <% if appointment.user.photo.attached? %>
        <%= image_tag cl_image_path(appointment.user.photo.key), alt: 'Profile User Photo', class: 'img-card-appointment mx-4' %>
      <% else %>
        <%= image_tag asset_path('counsellor.png'), alt: 'Default Profile Photo', class: 'img-card-appointment mx-4' %>
      <% end %>
      <% if appointment.counsellor.photo.attached? %>
        <%= image_tag cl_image_path(appointment.counsellor.photo.key), alt: 'Profile Counsellor Photo', class: 'img-card-appointment mx-4' %>
      <% end %>
    </div>
    <div class="ps-2">
      <h5 class="card-title"><strong><%= appointment.user.fullname %></strong></h5>
      <p class="card-text"><%= appointment.symptom %></p>
      <p> <strong>Schedule Time:</strong>
        <%= appointment.schedule_time.strftime("%B %d, %Y at %I:%M %p") %>
      </p>
      <% if appointment.confirmation %>
        <% chatroom = ClientChatroom.find_by(user_id: appointment.user_id, counsellor_id: appointment.counsellor_id) %>
        <% if chatroom.present? %>
          <%= link_to 'Your Talkroom', client_chatroom_path(chatroom), class: 'btn-appointment justify-content-center mb-2' %>
        <% elsif %>
          <%= button_to 'Create Talkroom', client_chatrooms_path(user_id: appointment.user_id, counsellor_id: appointment.counsellor_id), method: :post, class: 'btn-appointment justify-content-center mb-2' %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="d-flex flex-column ms-2">
    <%= link_to appointment_path(appointment), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
      <i class="text-white fa-sharp fa-solid fa-trash btn btn-danger btn-lg rounded-circle"></i>
    <% end %>

    <%= link_to edit_appointment_path(appointment) do %>
      <i class="fa-solid fa-pen-to-square btn btn-primary btn-lg rounded-circle mt-4"></i>
    <% end %>
  </div>
</div>

app/views/counsellors/profile.html.erb
<div class="profile-background">
  <div class="container profile-border">
    <h1>Welcome</h1>
    <p>
      Hello and welcome to TalkRoom, a platform dedicated to providing accessible mental health support while helping you gain valuable real-world experience. We are thrilled to have you join our team of passionate and compassionate counsellors.
    </p>
  </div>
</div>

<div class="container mt-4">
  <div class="row counsellor-data">
    <div class="col-12 col-lg-4 align-content-center mb-4">
      <%= image_tag cl_image_path(current_counsellor.photo.key), alt: 'Profile Patient', class: 'rounded-circle profile-image img-fluid mb-2' %>
    </div>
    <div class="col-12 col-lg-8">
      <p><strong>Email:</strong> <%= @counsellor.email %></p>
      <p><strong>Full Name:</strong> <%= @counsellor.fullname %></p>
      <p><strong>Gender:</strong> <%= @counsellor.gender %></p>
      <p><strong>Location:</strong> <%= @counsellor.address %></p>
      <p><strong>Date of Birth:</strong> <%= @counsellor.birthdate.strftime("%B %d, %Y") if @counsellor.birthdate %></p>
      <p><strong>University Name:</strong> <%= @counsellor.university_name %></p>
      <p><strong>University ID:</strong> <%= @counsellor.university_id %></p>
      <p><strong>Degree Program:</strong> <%= @counsellor.degree_program %></p>
      <p><strong>Year of Study:</strong> <%= @counsellor.year_of_study %></p>
      <p><strong>Expected Graduation Date:</strong> <%= @counsellor.expected_graduation_date %></p>
      <div class="mt-3">
        <%= link_to 'Change Password', edit_counsellor_registration_path, class: 'btn-homepage' %>
      </div>
    </div>
  </div>
</div>

<div class="container-previous-appointments-margin-top d-flex justify-content-center">
  <div data-controller="appointments" class="col-12 col-md-8">
    <div class="row justify-content-center <%= 'scroller' if @appointments.any? %> pt-2" data-appointments-target="appointments">
      <% @appointments.order(created_at: :desc).each_with_index do |appointment, index| %>
        <%= render "pending_appointments", appointment: appointment, index: index %>
      <% end %>
    </div>
  </div>
</div>

<div class="big-tag w-100 mt-4">
  <%= image_tag 'home8.png', loading: 'lazy', class: 'imag1 img-fluid' %>
  <div class="big-tag2 mt-3">
    <h1>Taking care of your mental health is essential for your overall well-being</h1>
    <%= image_tag 'home7.png', loading: 'lazy', class: 'imag2 img-fluid' %>
  </div>
</div>

<div class="previous-title mt-4">
  On-going Appointments
</div>

<div class="container previous-appointments d-flex flex-column flex-md-row justify-content-center">
  <div class="col-12 col-md-4 mb-4">
    <%= image_tag asset_path('counsellor2.png'), alt: 'Default Profile Photo', class: 'img-counsell img-fluid' %>
  </div>
  <div id="carouselPreviousAppointments" class="carousel slide col-12 col-md-8">
    <div class="carousel-inner">
      <% @appointments_confirmed.order(created_at: :desc).each_with_index do |appointment, index| %>
        <div class="carousel-item <%= 'active' if index == 0 %>">
          <div class="row justify-content-center pt-2">
            <%= render 'counsellors/previous_appointment_counsellor', appointment: appointment %>
          </div>
        </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselPreviousAppointments" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselPreviousAppointments" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>